name: Test Github Actions  


on:   
  push:     
    branches: ['main']   
      
      
      
jobs: 
  my-example-job:
    runs-on: unbuntu-latest      
    steps:       
      - name: checkout code         
        uses: actions/checkout@v5.0.0                
      
      - name: print hello world         
        run: echo "Hello world"                 
